#!/usr/bin/bash
#set -x

CHIA=/usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chia
CHIA_STOP_PARAMETERS='stop -d all'
CHIA_START_PARAMETERS='start farmer'

SOURCE=db
CURRENT_SOURCE_DIRECTORY=/home/chiapi/.chia/mainnet
CURRENT_SOURCE_PATH="${CURRENT_SOURCE_DIRECTORY}"/"${SOURCE}"
BACKUP_DESTINATION_DIRECTORY=/media/chiapi/ChiaPlots2/db-backups
BACKUP_DESTINATION_PATH="$BACKUP_DESTINATION_DIRECTORY"/"${SOURCE}".1

NUMBER_OF_BACKUPS=3

cat<<EOF
Beginning to backup Chia blockchain database
EOF

set +e
CHIA_PROCESSES=$(ps auxwwww | tr -s ' ' | cut -d ' ' -f 11 | grep chia | grep -v chiapi | grep -E "^chia_")
cat<<EOF
$CHIA_PROCESSES
EOF
set -e

if [[ -z "${CHIA_PROCESSES}" ]]; then
    echo 'No Chia processes present'
else
    echo 'There are Chia processes running so shutting down Chia'
    $CHIA $CHIA_STOP_PARAMETERS
fi

# Move any existing backups one over
for ((bn=$NUMBER_OF_BACKUPS;bn>1;bn-=1)); do
    PREV_NUMBER=$(($bn-1))
    CURRENT_BACKUP_NAME="${BACKUP_DESTINATION_DIRECTORY}/${SOURCE}.${PREV_NUMBER}"
    NEXT_BACKUP_NAME="${BACKUP_DESTINATION_DIRECTORY}/${SOURCE}.${bn}"
    echo "Checking if ${CURRENT_BACKUP_NAME} exists"
    if [[ -e "${CURRENT_BACKUP_NAME}" ]]; then
    	echo "It does! Moving to ${NEXT_BACKUP_NAME}"
        mv "${CURRENT_BACKUP_NAME}" "${NEXT_BACKUP_NAME}"
	echo "Moved!"
    else
        echo "No file at ${CURRENT_BACKUP_NAME} to move"
    fi
done

# Copy the current file now
cat<<EOF
Copying ${CURRENT_SOURCE_PATH} to ${DESTINATION_BACKUP_PATH}
#Copying $CURRENT_DATABASE_PATH to $DESTINATION_BACKUP_PATH
EOF

tar -cvf "${BACKUP_DESTINATION_PATH}" -C "${CURRENT_SOURCE_DIRECTORY}" "${SOURCE}"
cat<<EOF
Copied!
EOF

cat<<EOF
Restart Chia
EOF

$CHIA $CHIA_START_PARAMETERS
set +ex
